---
{{- $metricConfig := (merge (dict "name" "metric-agent" "module" "metrics" "containerName" "metric-agent") .) -}}

{{- if .Values.metricAgent.enable }}

apiVersion: v1 
data: 
  liqo-cert-req.conf: |+ 
    [req] 
    req_extensions = v3_req 
    distinguished_name = req_distinguished_name 
    prompt = no 
    [req_distinguished_name]
    C = IT 
    ST = Turin 
    O = Liqo 
    [v3_req] 
    keyUsage = keyEncipherment, dataEncipherment 
    extendedKeyUsage = serverAuth 
    subjectAltName = @alt_names 
    [alt_names] 
    DNS.1 = liqo-metric-agent.liqo.svc.cluster.local 

kind: ConfigMap 
metadata: 
  name: san-liqo-metric 
  namespace: liqo
  labels:
    {{- include "liqo.labels" $metricConfig | nindent 4 }}

{{- end }}