---
apiVersion: v1 
data: 
  liqo-cert-req.conf: |+ 
    [req] 
    req_extensions = v3_req 
    distinguished_name = req_distinguished_name 
    prompt = no 
    [req_distinguished_name]
    C = IT 
    ST = Turin 
    O = Liqo 
    [v3_req] 
    keyUsage = keyEncipherment, dataEncipherment 
    extendedKeyUsage = serverAuth 
    subjectAltName = @alt_names 
    [alt_names] 
    DNS.1 = liqo-auth.liqo.svc.cluster.local 

kind: ConfigMap 
metadata: 
  name: san-liqo-auth
  namespace: liqo